### ISSUE TITLE
When the PG database encounters multiple columns with SUM returns, the system defaults to returning the same value

### ISSUE THREAD

**Issue by mxli441** [tencentmusic/supersonic#920] opened 2024-04-18 08:58 UTC
when I  asking a question with multiple columns with sum returns
![image](https://github.com/tencentmusic/supersonic/assets/70192192/c075059c-d197-4446-83ab-1bcd6c034103)

It is normal when using multiple columns with sum returns
![bd090f12b7ca3ea9c293102d3e36360](https://github.com/tencentmusic/supersonic/assets/70192192/8af42a72-1d87-4bc9-8e68-fb9b83bcc742)

so,I think it is a bug,please repair it as soon as quickly.

**Comment by lexluo09** [comment] 2024-04-24 07:11
Thank you for your suggestion.

**Comment by jipeli** [comment] 2024-04-26 10:51
Duplicate of #951

**Closed as completed by jipeli** 2024-04-26 10:51 UTC
